// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package recognizer

import (
	"context"
	"sync"
)

// Ensure, that AudioReaderInterfaceMock does implement AudioReaderInterface.
// If this is not the case, regenerate this file with moq.
var _ AudioReaderInterface = &AudioReaderInterfaceMock{}

// AudioReaderInterfaceMock is a mock implementation of AudioReaderInterface.
//
//	func TestSomethingThatUsesAudioReaderInterface(t *testing.T) {
//
//		// make and configure a mocked AudioReaderInterface
//		mockedAudioReaderInterface := &AudioReaderInterfaceMock{
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedAudioReaderInterface in code that requires AudioReaderInterface
//		// and then make assertions.
//
//	}
type AudioReaderInterfaceMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *AudioReaderInterfaceMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("AudioReaderInterfaceMock.StartFunc: method is nil but AudioReaderInterface.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedAudioReaderInterface.StartCalls())
func (mock *AudioReaderInterfaceMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
