// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package recognize

import (
	"context"
	"sync"
)

// Ensure, that ResponseReceiverInterfaceMock does implement ResponseReceiverInterface.
// If this is not the case, regenerate this file with moq.
var _ ResponseReceiverInterface = &ResponseReceiverInterfaceMock{}

// ResponseReceiverInterfaceMock is a mock implementation of ResponseReceiverInterface.
//
//	func TestSomethingThatUsesResponseReceiverInterface(t *testing.T) {
//
//		// make and configure a mocked ResponseReceiverInterface
//		mockedResponseReceiverInterface := &ResponseReceiverInterfaceMock{
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedResponseReceiverInterface in code that requires ResponseReceiverInterface
//		// and then make assertions.
//
//	}
type ResponseReceiverInterfaceMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *ResponseReceiverInterfaceMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("ResponseReceiverInterfaceMock.StartFunc: method is nil but ResponseReceiverInterface.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedResponseReceiverInterface.StartCalls())
func (mock *ResponseReceiverInterfaceMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
