// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package recognize

import (
	"context"
	"sync"
)

// Ensure, that StreamSupplierInterfaceMock does implement StreamSupplierInterface.
// If this is not the case, regenerate this file with moq.
var _ StreamSupplierInterface = &StreamSupplierInterfaceMock{}

// StreamSupplierInterfaceMock is a mock implementation of StreamSupplierInterface.
//
//	func TestSomethingThatUsesStreamSupplierInterface(t *testing.T) {
//
//		// make and configure a mocked StreamSupplierInterface
//		mockedStreamSupplierInterface := &StreamSupplierInterfaceMock{
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//			SupplyFunc: func(ctx context.Context) error {
//				panic("mock out the Supply method")
//			},
//		}
//
//		// use mockedStreamSupplierInterface in code that requires StreamSupplierInterface
//		// and then make assertions.
//
//	}
type StreamSupplierInterfaceMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// SupplyFunc mocks the Supply method.
	SupplyFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Supply holds details about calls to the Supply method.
		Supply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockStart  sync.RWMutex
	lockSupply sync.RWMutex
}

// Start calls StartFunc.
func (mock *StreamSupplierInterfaceMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("StreamSupplierInterfaceMock.StartFunc: method is nil but StreamSupplierInterface.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedStreamSupplierInterface.StartCalls())
func (mock *StreamSupplierInterfaceMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Supply calls SupplyFunc.
func (mock *StreamSupplierInterfaceMock) Supply(ctx context.Context) error {
	if mock.SupplyFunc == nil {
		panic("StreamSupplierInterfaceMock.SupplyFunc: method is nil but StreamSupplierInterface.Supply was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSupply.Lock()
	mock.calls.Supply = append(mock.calls.Supply, callInfo)
	mock.lockSupply.Unlock()
	return mock.SupplyFunc(ctx)
}

// SupplyCalls gets all the calls that were made to Supply.
// Check the length with:
//
//	len(mockedStreamSupplierInterface.SupplyCalls())
func (mock *StreamSupplierInterfaceMock) SupplyCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSupply.RLock()
	calls = mock.calls.Supply
	mock.lockSupply.RUnlock()
	return calls
}
