// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package speechpb

import (
	"cloud.google.com/go/speech/apiv2/speechpb"
	"context"
	"google.golang.org/grpc/metadata"
	"sync"
)

// Ensure, that Speech_StreamingRecognizeClientMock does implement Speech_StreamingRecognizeClient.
// If this is not the case, regenerate this file with moq.
var _ Speech_StreamingRecognizeClient = &Speech_StreamingRecognizeClientMock{}

// Speech_StreamingRecognizeClientMock is a mock implementation of Speech_StreamingRecognizeClient.
//
//	func TestSomethingThatUsesSpeech_StreamingRecognizeClient(t *testing.T) {
//
//		// make and configure a mocked Speech_StreamingRecognizeClient
//		mockedSpeech_StreamingRecognizeClient := &Speech_StreamingRecognizeClientMock{
//			CloseSendFunc: func() error {
//				panic("mock out the CloseSend method")
//			},
//			ContextFunc: func() context.Context {
//				panic("mock out the Context method")
//			},
//			HeaderFunc: func() (metadata.MD, error) {
//				panic("mock out the Header method")
//			},
//			RecvFunc: func() (*speechpb.StreamingRecognizeResponse, error) {
//				panic("mock out the Recv method")
//			},
//			RecvMsgFunc: func(m any) error {
//				panic("mock out the RecvMsg method")
//			},
//			SendFunc: func(streamingRecognizeRequest *speechpb.StreamingRecognizeRequest) error {
//				panic("mock out the Send method")
//			},
//			SendMsgFunc: func(m any) error {
//				panic("mock out the SendMsg method")
//			},
//			TrailerFunc: func() metadata.MD {
//				panic("mock out the Trailer method")
//			},
//		}
//
//		// use mockedSpeech_StreamingRecognizeClient in code that requires Speech_StreamingRecognizeClient
//		// and then make assertions.
//
//	}
type Speech_StreamingRecognizeClientMock struct {
	// CloseSendFunc mocks the CloseSend method.
	CloseSendFunc func() error

	// ContextFunc mocks the Context method.
	ContextFunc func() context.Context

	// HeaderFunc mocks the Header method.
	HeaderFunc func() (metadata.MD, error)

	// RecvFunc mocks the Recv method.
	RecvFunc func() (*speechpb.StreamingRecognizeResponse, error)

	// RecvMsgFunc mocks the RecvMsg method.
	RecvMsgFunc func(m any) error

	// SendFunc mocks the Send method.
	SendFunc func(streamingRecognizeRequest *speechpb.StreamingRecognizeRequest) error

	// SendMsgFunc mocks the SendMsg method.
	SendMsgFunc func(m any) error

	// TrailerFunc mocks the Trailer method.
	TrailerFunc func() metadata.MD

	// calls tracks calls to the methods.
	calls struct {
		// CloseSend holds details about calls to the CloseSend method.
		CloseSend []struct {
		}
		// Context holds details about calls to the Context method.
		Context []struct {
		}
		// Header holds details about calls to the Header method.
		Header []struct {
		}
		// Recv holds details about calls to the Recv method.
		Recv []struct {
		}
		// RecvMsg holds details about calls to the RecvMsg method.
		RecvMsg []struct {
			// M is the m argument value.
			M any
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// StreamingRecognizeRequest is the streamingRecognizeRequest argument value.
			StreamingRecognizeRequest *speechpb.StreamingRecognizeRequest
		}
		// SendMsg holds details about calls to the SendMsg method.
		SendMsg []struct {
			// M is the m argument value.
			M any
		}
		// Trailer holds details about calls to the Trailer method.
		Trailer []struct {
		}
	}
	lockCloseSend sync.RWMutex
	lockContext   sync.RWMutex
	lockHeader    sync.RWMutex
	lockRecv      sync.RWMutex
	lockRecvMsg   sync.RWMutex
	lockSend      sync.RWMutex
	lockSendMsg   sync.RWMutex
	lockTrailer   sync.RWMutex
}

// CloseSend calls CloseSendFunc.
func (mock *Speech_StreamingRecognizeClientMock) CloseSend() error {
	if mock.CloseSendFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.CloseSendFunc: method is nil but Speech_StreamingRecognizeClient.CloseSend was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCloseSend.Lock()
	mock.calls.CloseSend = append(mock.calls.CloseSend, callInfo)
	mock.lockCloseSend.Unlock()
	return mock.CloseSendFunc()
}

// CloseSendCalls gets all the calls that were made to CloseSend.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.CloseSendCalls())
func (mock *Speech_StreamingRecognizeClientMock) CloseSendCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCloseSend.RLock()
	calls = mock.calls.CloseSend
	mock.lockCloseSend.RUnlock()
	return calls
}

// Context calls ContextFunc.
func (mock *Speech_StreamingRecognizeClientMock) Context() context.Context {
	if mock.ContextFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.ContextFunc: method is nil but Speech_StreamingRecognizeClient.Context was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContext.Lock()
	mock.calls.Context = append(mock.calls.Context, callInfo)
	mock.lockContext.Unlock()
	return mock.ContextFunc()
}

// ContextCalls gets all the calls that were made to Context.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.ContextCalls())
func (mock *Speech_StreamingRecognizeClientMock) ContextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContext.RLock()
	calls = mock.calls.Context
	mock.lockContext.RUnlock()
	return calls
}

// Header calls HeaderFunc.
func (mock *Speech_StreamingRecognizeClientMock) Header() (metadata.MD, error) {
	if mock.HeaderFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.HeaderFunc: method is nil but Speech_StreamingRecognizeClient.Header was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHeader.Lock()
	mock.calls.Header = append(mock.calls.Header, callInfo)
	mock.lockHeader.Unlock()
	return mock.HeaderFunc()
}

// HeaderCalls gets all the calls that were made to Header.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.HeaderCalls())
func (mock *Speech_StreamingRecognizeClientMock) HeaderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHeader.RLock()
	calls = mock.calls.Header
	mock.lockHeader.RUnlock()
	return calls
}

// Recv calls RecvFunc.
func (mock *Speech_StreamingRecognizeClientMock) Recv() (*speechpb.StreamingRecognizeResponse, error) {
	if mock.RecvFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.RecvFunc: method is nil but Speech_StreamingRecognizeClient.Recv was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRecv.Lock()
	mock.calls.Recv = append(mock.calls.Recv, callInfo)
	mock.lockRecv.Unlock()
	return mock.RecvFunc()
}

// RecvCalls gets all the calls that were made to Recv.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.RecvCalls())
func (mock *Speech_StreamingRecognizeClientMock) RecvCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRecv.RLock()
	calls = mock.calls.Recv
	mock.lockRecv.RUnlock()
	return calls
}

// RecvMsg calls RecvMsgFunc.
func (mock *Speech_StreamingRecognizeClientMock) RecvMsg(m any) error {
	if mock.RecvMsgFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.RecvMsgFunc: method is nil but Speech_StreamingRecognizeClient.RecvMsg was just called")
	}
	callInfo := struct {
		M any
	}{
		M: m,
	}
	mock.lockRecvMsg.Lock()
	mock.calls.RecvMsg = append(mock.calls.RecvMsg, callInfo)
	mock.lockRecvMsg.Unlock()
	return mock.RecvMsgFunc(m)
}

// RecvMsgCalls gets all the calls that were made to RecvMsg.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.RecvMsgCalls())
func (mock *Speech_StreamingRecognizeClientMock) RecvMsgCalls() []struct {
	M any
} {
	var calls []struct {
		M any
	}
	mock.lockRecvMsg.RLock()
	calls = mock.calls.RecvMsg
	mock.lockRecvMsg.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *Speech_StreamingRecognizeClientMock) Send(streamingRecognizeRequest *speechpb.StreamingRecognizeRequest) error {
	if mock.SendFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.SendFunc: method is nil but Speech_StreamingRecognizeClient.Send was just called")
	}
	callInfo := struct {
		StreamingRecognizeRequest *speechpb.StreamingRecognizeRequest
	}{
		StreamingRecognizeRequest: streamingRecognizeRequest,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(streamingRecognizeRequest)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.SendCalls())
func (mock *Speech_StreamingRecognizeClientMock) SendCalls() []struct {
	StreamingRecognizeRequest *speechpb.StreamingRecognizeRequest
} {
	var calls []struct {
		StreamingRecognizeRequest *speechpb.StreamingRecognizeRequest
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// SendMsg calls SendMsgFunc.
func (mock *Speech_StreamingRecognizeClientMock) SendMsg(m any) error {
	if mock.SendMsgFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.SendMsgFunc: method is nil but Speech_StreamingRecognizeClient.SendMsg was just called")
	}
	callInfo := struct {
		M any
	}{
		M: m,
	}
	mock.lockSendMsg.Lock()
	mock.calls.SendMsg = append(mock.calls.SendMsg, callInfo)
	mock.lockSendMsg.Unlock()
	return mock.SendMsgFunc(m)
}

// SendMsgCalls gets all the calls that were made to SendMsg.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.SendMsgCalls())
func (mock *Speech_StreamingRecognizeClientMock) SendMsgCalls() []struct {
	M any
} {
	var calls []struct {
		M any
	}
	mock.lockSendMsg.RLock()
	calls = mock.calls.SendMsg
	mock.lockSendMsg.RUnlock()
	return calls
}

// Trailer calls TrailerFunc.
func (mock *Speech_StreamingRecognizeClientMock) Trailer() metadata.MD {
	if mock.TrailerFunc == nil {
		panic("Speech_StreamingRecognizeClientMock.TrailerFunc: method is nil but Speech_StreamingRecognizeClient.Trailer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTrailer.Lock()
	mock.calls.Trailer = append(mock.calls.Trailer, callInfo)
	mock.lockTrailer.Unlock()
	return mock.TrailerFunc()
}

// TrailerCalls gets all the calls that were made to Trailer.
// Check the length with:
//
//	len(mockedSpeech_StreamingRecognizeClient.TrailerCalls())
func (mock *Speech_StreamingRecognizeClientMock) TrailerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTrailer.RLock()
	calls = mock.calls.Trailer
	mock.lockTrailer.RUnlock()
	return calls
}
