name: "lint and test"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v4"
      - name: install MeCab
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
          echo "CGO_LDFLAGS=$(mecab-config --libs)" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$(mecab-config --inc-dir)" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v4"
      - name: install MeCab
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
          echo "CGO_LDFLAGS=$(mecab-config --libs)" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$(mecab-config --inc-dir)" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Test
        run: go test -cover -race -timeout 10s ./...
