name: "lint and test"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v4"
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: create includes directory
        run: mkdir -p lib/vosk
      - name: fetch vsok_api.h
        run: curl -sSL https://raw.githubusercontent.com/alphacep/vosk-api/refs/tags/v0.3.42/src/vosk_api.h -o lib/vosk/vosk_api.h
      - name: add vosk to include path
        run: echo "CGO_CFLAGS=-I$(pwd)/lib/vosk" >> $GITHUB_ENV
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v4"
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: create includes directory
        run: mkdir -p lib/vosk
      - name: fetch vsok_api.h
        run: curl -sSL https://raw.githubusercontent.com/alphacep/vosk-api/refs/tags/v0.3.42/src/vosk_api.h -o lib/vosk/vosk_api.h
      - name: Run Test
        run: CGO_CFLAGS="-I $(pwd)/lib/vosk" go test -cover -race -timeout 10s ./...
